# Generated by Django 2.2.4 on 2019-08-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0002_auto_20190810_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='img',
            field=models.ImageField(default='null', upload_to='pics'),
        ),
    ]
